# Copyright (C) 2011-2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/pantech/ef63s/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
	vendor/pantech/ef63s/proprietary/vendor/lib/libacdbloader.so:obj/vendor/lib/libacdbloader.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libaudioalsa.so:obj/vendor/lib/libaudioalsa.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libtime_genoff.so:obj/lib/libtime_genoff.so

# Proprietary files
PRODUCT_COPY_FILES += \
	vendor/pantech/ef63s/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
	vendor/pantech/ef63s/proprietary/bin/install-recovery.sh:system/bin/install-recovery.sh \
	vendor/pantech/ef63s/proprietary/bin/location-mq:system/bin/location-mq \
	vendor/pantech/ef63s/proprietary/bin/qseecom_sample_client:system/bin/qseecom_sample_client \
	vendor/pantech/ef63s/proprietary/bin/qseecom_security_test:system/bin/qseecom_security_test \
	vendor/pantech/ef63s/proprietary/bin/quipc_igsn:system/bin/quipc_igsn \
	vendor/pantech/ef63s/proprietary/bin/quipc_main:system/bin/quipc_main \
	vendor/pantech/ef63s/proprietary/bin/shbtnvtool:system/bin/shbtnvtool \
	vendor/pantech/ef63s/proprietary/vendor/lib/libaudioalsa.so:system/vendor/lib/libaudioalsa.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libacdbmapper.so:system/vendor/lib/libacdbmapper.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libc2d30.so:system/vendor/lib/libc2d30.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libOpenVG.so:system/vendor/lib/libOpenVG.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
	vendor/pantech/ef63s/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
	vendor/pantech/ef63s/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
	vendor/pantech/ef63s/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
	vendor/pantech/ef63s/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
	vendor/pantech/ef63s/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
	vendor/pantech/ef63s/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
	vendor/pantech/ef63s/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
	vendor/pantech/ef63s/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
	vendor/pantech/ef63s/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
	vendor/pantech/ef63s/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
	vendor/pantech/ef63s/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
	vendor/pantech/ef63s/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
	vendor/pantech/ef63s/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
	vendor/pantech/ef63s/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
	vendor/pantech/ef63s/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
	vendor/pantech/ef63s/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
	vendor/pantech/ef63s/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
	vendor/pantech/ef63s/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
	vendor/pantech/ef63s/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx135_common.so:system/vendor/lib/libchromatix_imx135_common.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx135_default_video.so:system/vendor/lib/libchromatix_imx135_default_video.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx135_hfr_120.so:system/vendor/lib/libchromatix_imx135_hfr_120.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx135_preview.so:system/vendor/lib/libchromatix_imx135_preview.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx135_snapshot.so:system/vendor/lib/libchromatix_imx135_snapshot.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx135_video_hd.so:system/vendor/lib/libchromatix_imx135_video_hd.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx135_hfr_60.so:system/vendor/lib/libchromatix_imx135_hfr_60.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx135_hfr_90.so:system/vendor/lib/libchromatix_imx135_hfr_90.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libcneqmiutils.so:system/vendor/lib/libcneqmiutils.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libcneutils.so:system/vendor/lib/libcneutils.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libcneconn.so:system/vendor/lib/libcneconn.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libCommandSvc.so:system/vendor/lib/libCommandSvc.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libdrmdiag.so:system/vendor/lib/libdrmdiag.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libdsnetutils.so:system/vendor/lib/libdsnetutils.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libepdsp.so:system/vendor/lib/libepdsp.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libFileMux.so:system/vendor/lib/libFileMux.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libHevcSwDecoder.so:system/vendor/lib/libHevcSwDecoder.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_imx135.so:system/vendor/lib/libmmcamera_imx135.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmhttpstack.so:system/vendor/lib/libmmhttpstack.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmiipstreammmihttp.so:system/vendor/lib/libmmiipstreammmihttp.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmipstreamaal.so:system/vendor/lib/libmmipstreamaal.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmipstreamnetwork.so:system/vendor/lib/libmmipstreamnetwork.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmipstreamsourcehttp.so:system/vendor/lib/libmmipstreamsourcehttp.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmipstreamutils.so:system/vendor/lib/libmmipstreamutils.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmQSM.so:system/vendor/lib/libmmQSM.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmrtpdecoder.so:system/vendor/lib/libmmrtpdecoder.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmrtpencoder.so:system/vendor/lib/libmmrtpencoder.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmwfdinterface.so:system/vendor/lib/libmmwfdinterface.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmwfdsinkinterface.so:system/vendor/lib/libmmwfdsinkinterface.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmwfdsrcinterface.so:system/vendor/lib/libmmwfdsrcinterface.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libNimsWrap.so:system/vendor/lib/libNimsWrap.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libOmxAmrwbplusDec.so:system/vendor/lib/libOmxAmrwbplusDec.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libOmxMux.so:system/vendor/lib/libOmxMux.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libOmxWmaDec.so:system/vendor/lib/libOmxWmaDec.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libP11Notify.so:system/vendor/lib/libP11Notify.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libprdrmdecrypt.so:system/vendor/lib/libprdrmdecrypt.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libprofiler_msmadc.so:system/vendor/lib/libprofiler_msmadc.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libqcgesture.so:system/vendor/lib/libqcgesture.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libqmi_csvt_srvc.so:system/vendor/lib/libqmi_csvt_srvc.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/hw/sensors.msm8974.so:system/vendor/lib/hw/sensors.msm8974.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libwfdcommonutils.so:system/vendor/lib/libwfdcommonutils.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libwfdhdcpcp.so:system/vendor/lib/libwfdhdcpcp.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libwfdmmsink.so:system/vendor/lib/libwfdmmsink.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libwfdmmsrc.so:system/vendor/lib/libwfdmmsrc.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libwfdmmutils.so:system/vendor/lib/libwfdmmutils.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libwfdnative.so:system/vendor/lib/libwfdnative.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libwfdrtsp.so:system/vendor/lib/libwfdrtsp.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libwfdsm.so:system/vendor/lib/libwfdsm.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libwfduibcinterface.so:system/vendor/lib/libwfduibcinterface.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libwfduibcsinkinterface.so:system/vendor/lib/libwfduibcsinkinterface.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libwfduibcsink.so:system/vendor/lib/libwfduibcsink.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libwfduibcsrcinterface.so:system/vendor/lib/libwfduibcsrcinterface.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libwfduibcsrc.so:system/vendor/lib/libwfduibcsrc.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
	vendor/pantech/ef63s/proprietary/lib/libcnefeatureconfig.so:system/lib/libcnefeatureconfig.so \
	vendor/pantech/ef63s/proprietary/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
	vendor/pantech/ef63s/proprietary/lib/libqsap_sdk.so:system/lib/libqsap_sdk.so \
	vendor/pantech/ef63s/proprietary/bin/irsc_util:system/bin/irsc_util \
	vendor/pantech/ef63s/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
	vendor/pantech/ef63s/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
	vendor/pantech/ef63s/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
	vendor/pantech/ef63s/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
	vendor/pantech/ef63s/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
	vendor/pantech/ef63s/proprietary/bin/efsks:system/bin/efsks \
	vendor/pantech/ef63s/proprietary/bin/ks:system/bin/ks \
	vendor/pantech/ef63s/proprietary/bin/netmgrd:system/bin/netmgrd \
	vendor/pantech/ef63s/proprietary/bin/qcks:system/bin/qcks \
	vendor/pantech/ef63s/proprietary/bin/qseecomd:system/bin/qseecomd \
	vendor/pantech/ef63s/proprietary/bin/radish:system/bin/radish \
	vendor/pantech/ef63s/proprietary/bin/rfs_access:system/bin/rfs_access \
	vendor/pantech/ef63s/proprietary/bin/rmt_storage:system/bin/rmt_storage \
	vendor/pantech/ef63s/proprietary/bin/qmuxd:system/bin/qmuxd \
	vendor/pantech/ef63s/proprietary/bin/qmiproxy:system/bin/qmiproxy \
	vendor/pantech/ef63s/proprietary/bin/rild:system/bin/rild \
	vendor/pantech/ef63s/proprietary/bin/time_daemon:system/bin/time_daemon \
	vendor/pantech/ef63s/proprietary/bin/ssr_diag:system/bin/ssr_diag \
	vendor/pantech/ef63s/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libSSEPKCS11.so:system/vendor/lib/libSSEPKCS11.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libsubsystem_control.so:system/vendor/lib/libsubsystem_control.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libtzdrmgenprov.so:system/vendor/lib/libtzdrmgenprov.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libtzplayready.so:system/vendor/lib/libtzplayready.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
	vendor/pantech/ef63s/proprietary/lib/libbinder.so:system/lib/libbinder.so \
	vendor/pantech/ef63s/proprietary/lib/libsymbols.so:system/lib/libsymbols.so 

PRODUCT_COPY_FILES += \
	vendor/pantech/ef63s/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
	vendor/pantech/ef63s/proprietary/lib/hw/camera.msm8974.so:system/lib/hw/camera.msm8974.so \
	vendor/pantech/ef63s/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
	vendor/pantech/ef63s/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
	vendor/pantech/ef63s/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
	vendor/pantech/ef63s/proprietary/bin/mm-qcamera-app:system/bin/mm-qcamera-app \
	vendor/pantech/ef63s/proprietary/etc/cne/andsfCne.xml:system/etc/cne/andsfCne.xml \
	vendor/pantech/ef63s/proprietary/etc/cne/NsrmConfiguration.xml:system/etc/cne/NsrmConfiguration.xml \
	vendor/pantech/ef63s/proprietary/etc/cne/SwimConfig.xml:system/etc/cne/SwimConfig.xml \
	vendor/pantech/ef63s/proprietary/lib/modules/texfat.ko:system/lib/modules/texfat.ko \
	vendor/pantech/ef63s/proprietary/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmm-hdcpmgr.so:system/vendor/lib/libmm-hdcpmgr.so\
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmQTA.so:system/vendor/lib/libmmQTA.so\
	vendor/pantech/ef63s/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libyas530.so:system/vendor/lib/libyas530.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libquipc_ulp_adapter.so:system/vendor/lib/libquipc_ulp_adapter.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
	vendor/pantech/ef63s/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
	vendor/pantech/ef63s/proprietary/etc/permissions/com.google.widevine.software.drm.xml:system/etc/permissions/com.google.widevine.software.drm.xml \
	vendor/pantech/ef63s/proprietary/lib/libsky_rawdata.so:system/lib/libsky_rawdata.so \
	vendor/pantech/ef63s/proprietary/lib/libskytestclient.so:system/lib/libskytestclient.so \
	vendor/pantech/ef63s/proprietary/media/vega_usb.iso:system/media/vega_usb.iso \
	vendor/pantech/ef63s/proprietary/lib/libsnsutils.so:system/lib/libsnsutils.so\
	vendor/pantech/ef63s/proprietary/lib/libqctdspsreg.so:system/lib/libqctdspsreg.so\
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so 

PRODUCT_COPY_FILES += \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx134_common.so:system/vendor/lib/libchromatix_imx134_common.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx134_default_video.so:system/vendor/lib/libchromatix_imx134_default_video.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx134_hfr_120.so:system/vendor/lib/libchromatix_imx134_hfr_120.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx134_hfr_60.so:system/vendor/lib/libchromatix_imx134_hfr_60.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx134_preview.so:system/vendor/lib/libchromatix_imx134_preview.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx134_snapshot.so:system/vendor/lib/libchromatix_imx134_snapshot.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx135_common.so:system/vendor/lib/libchromatix_imx135_common.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx135_default_video.so:system/vendor/lib/libchromatix_imx135_default_video.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx135_hfr_120.so:system/vendor/lib/libchromatix_imx135_hfr_120.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx135_hfr_60.so:system/vendor/lib/libchromatix_imx135_hfr_60.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx135_hfr_90.so:system/vendor/lib/libchromatix_imx135_hfr_90.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx135_preview.so:system/vendor/lib/libchromatix_imx135_preview.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx135_snapshot.so:system/vendor/lib/libchromatix_imx135_snapshot.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx135_video_hd.so:system/vendor/lib/libchromatix_imx135_video_hd.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx214_common.so:system/vendor/lib/libchromatix_imx214_common.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx214_default_video.so:system/vendor/lib/libchromatix_imx214_default_video.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx214_hfr_120.so:system/vendor/lib/libchromatix_imx214_hfr_120.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx214_preview.so:system/vendor/lib/libchromatix_imx214_preview.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx214_snapshot.so:system/vendor/lib/libchromatix_imx214_snapshot.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx214_video_hd.so:system/vendor/lib/libchromatix_imx214_video_hd.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov2720_common.so:system/vendor/lib/libchromatix_ov2720_common.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov2720_default_video.so:system/vendor/lib/libchromatix_ov2720_default_video.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov2720_hfr.so:system/vendor/lib/libchromatix_ov2720_hfr.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov2720_liveshot.so:system/vendor/lib/libchromatix_ov2720_liveshot.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov2720_preview.so:system/vendor/lib/libchromatix_ov2720_preview.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov2720_zsl.so:system/vendor/lib/libchromatix_ov2720_zsl.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_common.so:system/vendor/lib/libchromatix_ov5648_oty5f03_common.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so:system/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_preview.so:system/vendor/lib/libchromatix_ov5648_oty5f03_preview.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so:system/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_zsl.so:system/vendor/lib/libchromatix_ov5648_oty5f03_zsl.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8825_common.so:system/vendor/lib/libchromatix_ov8825_common.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8825_default_video.so:system/vendor/lib/libchromatix_ov8825_default_video.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8825_hfr_120fps.so:system/vendor/lib/libchromatix_ov8825_hfr_120fps.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8825_hfr_60fps.so:system/vendor/lib/libchromatix_ov8825_hfr_60fps.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8825_hfr_90fps.so:system/vendor/lib/libchromatix_ov8825_hfr_90fps.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8825_liveshot_hd.so:system/vendor/lib/libchromatix_ov8825_liveshot_hd.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8825_liveshot.so:system/vendor/lib/libchromatix_ov8825_liveshot.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8825_preview_hd.so:system/vendor/lib/libchromatix_ov8825_preview_hd.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8825_preview.so:system/vendor/lib/libchromatix_ov8825_preview.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8825_snapshot_hd.so:system/vendor/lib/libchromatix_ov8825_snapshot_hd.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8825_snapshot.so:system/vendor/lib/libchromatix_ov8825_snapshot.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8825_video_hd.so:system/vendor/lib/libchromatix_ov8825_video_hd.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8825_zsl.so:system/vendor/lib/libchromatix_ov8825_zsl.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_common.so:system/vendor/lib/libchromatix_ov8865_q8v18a_common.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so:system/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_preview.so:system/vendor/lib/libchromatix_ov8865_q8v18a_preview.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so:system/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so:system/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov9724_common.so:system/vendor/lib/libchromatix_ov9724_common.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov9724_default_video.so:system/vendor/lib/libchromatix_ov9724_default_video.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov9724_liveshot.so:system/vendor/lib/libchromatix_ov9724_liveshot.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_ov9724_preview.so:system/vendor/lib/libchromatix_ov9724_preview.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_s5k3l1yx_common.so:system/vendor/lib/libchromatix_s5k3l1yx_common.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_s5k3l1yx_default_video.so:system/vendor/lib/libchromatix_s5k3l1yx_default_video.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_s5k3l1yx_liveshot.so:system/vendor/lib/libchromatix_s5k3l1yx_liveshot.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_s5k3l1yx_preview.so:system/vendor/lib/libchromatix_s5k3l1yx_preview.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_s5k3l1yx_snapshot.so:system/vendor/lib/libchromatix_s5k3l1yx_snapshot.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_s5k3l1yx_video_hd.so:system/vendor/lib/libchromatix_s5k3l1yx_video_hd.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_s5k3l1yx_zsl.so:system/vendor/lib/libchromatix_s5k3l1yx_zsl.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_SKUAA_ST_gc0339_common.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_common.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_SKUAA_ST_gc0339_default_video.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_default_video.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_SKUAA_ST_gc0339_preview.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_preview.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_common.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_common.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_default_video.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_default_video.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_liveshot.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_liveshot.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_preview.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_preview.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_snapshot.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_snapshot.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_zsl.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_zsl.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_common.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_common.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_default_video.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_default_video.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_120fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_120fps.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_90fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_90fps.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_liveshot.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_liveshot.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_preview.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_preview.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_snapshot.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_snapshot.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_video_hd.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_video_hd.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_zsl.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_zsl.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_common.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_common.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_default_video.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_default_video.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_preview.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_preview.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_snapshot.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_snapshot.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_video_hd.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_video_hd.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_zsl.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_zsl.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_common.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_common.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_default_video.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_default_video.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_preview.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_preview.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_snapshot.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_snapshot.so \
	
PRODUCT_COPY_FILES += \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_hi256.so:system/vendor/lib/libmmcamera_hi256.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_imx134.so:system/vendor/lib/libmmcamera_imx134.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_imx135.so:system/vendor/lib/libmmcamera_imx135.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_imx214.so:system/vendor/lib/libmmcamera_imx214.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_mt9m114.so:system/vendor/lib/libmmcamera_mt9m114.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so:system/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_ov2720.so:system/vendor/lib/libmmcamera_ov2720.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_ov5648_oty5f03.so:system/vendor/lib/libmmcamera_ov5648_oty5f03.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_ov8825.so:system/vendor/lib/libmmcamera_ov8825.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_ov8865_q8v18a.so:system/vendor/lib/libmmcamera_ov8865_q8v18a.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_ov9724.so:system/vendor/lib/libmmcamera_ov9724.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_s5k3l1yx.so:system/vendor/lib/libmmcamera_s5k3l1yx.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so:system/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so:system/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so:system/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so:system/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so:system/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_sp1628.so:system/vendor/lib/libmmcamera_sp1628.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so:system/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so:system/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so:system/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_truly_cm7700_eeprom.so:system/vendor/lib/libmmcamera_truly_cm7700_eeprom.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
	
	
PRODUCT_COPY_FILES += \
	vendor/pantech/ef63s/proprietary/lib/libchromatix_imx135_liveshot.so:system/lib/libchromatix_imx135_liveshot.so\
	vendor/pantech/ef63s/proprietary/lib/libchromatix_imx214_liveshot.so:system/lib/libchromatix_imx214_liveshot.so\
	vendor/pantech/ef63s/proprietary/lib/libchromatix_imx214_zsl.so:system/lib/libchromatix_imx214_zsl.so\
	vendor/pantech/ef63s/proprietary/lib/libchromatix_s5k6b2yx_common.so:system/lib/libchromatix_s5k6b2yx_common.so\
	vendor/pantech/ef63s/proprietary/lib/libchromatix_s5k6b2yx_default_video.so:system/lib/libchromatix_s5k6b2yx_default_video.so\
	vendor/pantech/ef63s/proprietary/lib/libchromatix_s5k6b2yx_preview.so:system/lib/libchromatix_s5k6b2yx_preview.so\
	vendor/pantech/ef63s/proprietary/lib/libchromatix_s5k6b2yx_vt.so:system/lib/libchromatix_s5k6b2yx_vt.so\
	vendor/pantech/ef63s/proprietary/lib/libchromatix_s5k6b2yx_vt_common.so:system/lib/libchromatix_s5k6b2yx_vt_common.so \
	vendor/pantech/ef63s/proprietary/lib/libmmcamera_rohm_eeprom.so:system/lib/libmmcamera_rohm_eeprom.so\
	vendor/pantech/ef63s/proprietary/lib/libmmcamera_rumba_sa_eeprom.so:system/lib/libmmcamera_rumba_sa_eeprom.so\
	vendor/pantech/ef63s/proprietary/lib/libmmcamera_s5k6b2yx.so:system/lib/libmmcamera_s5k6b2yx.so\
	vendor/pantech/ef63s/proprietary/lib/libsky_access_nand.so:system/lib/libsky_access_nand.so\
	vendor/pantech/ef63s/proprietary/lib/libsky_aprlib.so:system/lib/libsky_aprlib.so:\
	vendor/pantech/ef63s/proprietary/lib/libsky_avclog.so:system/lib/libsky_avclog.so\
	vendor/pantech/ef63s/proprietary/lib/libsky_bluetooth.so:system/lib/libsky_bluetooth.so\
	vendor/pantech/ef63s/proprietary/lib/libsky_common.so:system/lib/libsky_common.so\
	vendor/pantech/ef63s/proprietary/lib/libsky_ctrl_drv.so:system/lib/libsky_ctrl_drv.so\
	vendor/pantech/ef63s/proprietary/lib/libsky_dload.so:system/lib/libsky_dload.so\
	vendor/pantech/ef63s/proprietary/lib/libsky_img_verify.so:system/lib/libsky_img_verify.so\
	vendor/pantech/ef63s/proprietary/lib/libsky_md5.so:system/lib/libsky_md5.so\
	vendor/pantech/ef63s/proprietary/lib/libsky_rflog.so:system/lib/libsky_rflog.so\
	vendor/pantech/ef63s/proprietary/lib/libsky_rftest.so:system/lib/libsky_rftest.so\
	vendor/pantech/ef63s/proprietary/lib/libsky_station.so:system/lib/libsky_station.so\
	vendor/pantech/ef63s/proprietary/lib/libsky_wifi.so:system/lib/libsky_wifi.so\
	vendor/pantech/ef63s/proprietary/lib/libskymotioncore.so:system/lib/libskymotioncore.so\
	vendor/pantech/ef63s/proprietary/lib/libskyreset.so:system/lib/libskyreset.so
	
	
PRODUCT_COPY_FILES += \
	vendor/pantech/ef63s/proprietary/vendor/firmware/libpn547_fw_platform.so:system/vendor/firmware/libpn547_fw_platform.so \
	vendor/pantech/ef63s/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
	vendor/pantech/ef63s/proprietary/vendor/firmware/libpn547_pku.so:system/vendor/firmware/libpn547_pku.so \
	vendor/pantech/ef63s/proprietary/vendor/firmware/TestInput.txt:system/vendor/firmware/TestInput.txt

PRODUCT_COPY_FILES += \
	vendor/pantech/ef63s/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/lib-dplmedia.so:system/vendor/lib/lib-dplmedia.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/lib-sec-disp.so:system/vendor/lib/lib-sec-disp.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libSecureUILib.so:system/vendor/lib/libSecureUILib.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx214_hfr_60.so:system/vendor/lib/libchromatix_imx214_hfr_60.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libchromatix_imx214_video_uhd.so:system/vendor/lib/libchromatix_imx214_video_uhd.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libmmgesture-bus2.so:system/vendor/lib/libmmgesture-bus2.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libscve.so:system/vendor/lib/libscve.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libscve_stub.so:system/vendor/lib/libscve_stub.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libsecureui.so:system/vendor/lib/libsecureui.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libwifiscanner.so:system/vendor/lib/libwifiscanner.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/rfsa/adsp/libdspCV_skel.so:system/vendor/lib/rfsa/adsp/libdspCV_skel.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp.so:system/vendor/lib/rfsa/adsp/libfastcvadsp.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so:system/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so \
	vendor/pantech/ef63s/proprietary/vendor/lib/rfsa/adsp/libscveT2T_skel.so:system/vendor/lib/rfsa/adsp/libscveT2T_skel.so 

PRODUCT_COPY_FILES += \
	vendor/pantech/ef63s/proprietary/etc/firmware-ef63s/venus.b01:system/etc/firmware-ef63s/venus.b01 \
	vendor/pantech/ef63s/proprietary/etc/firmware-ef63s/venus.mbn:system/etc/firmware-ef63s/venus.mbn \
	vendor/pantech/ef63s/proprietary/etc/firmware-ef63s/venus.mdt:system/etc/firmware-ef63s/venus.mdt \
	vendor/pantech/ef63s/proprietary/etc/firmware-ef63k/venus.b01:system/etc/firmware-ef63k/venus.b01 \
	vendor/pantech/ef63s/proprietary/etc/firmware-ef63k/venus.mbn:system/etc/firmware-ef63k/venus.mbn \
	vendor/pantech/ef63s/proprietary/etc/firmware-ef63k/venus.mdt:system/etc/firmware-ef63k/venus.mdt 

PRODUCT_COPY_FILES += \
	vendor/pantech/ef63s/proprietary/framework/com.google.widevine.software.drm.jar:system/framework/com.google.widevine.software.drm.jar 

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/pantech/ef63s/proprietary/app,system/app)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/pantech/ef63s/proprietary/bin,system/bin)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/pantech/ef63s/proprietary/lib,system/lib)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/pantech/ef63s/proprietary/etc,system/etc)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/pantech/ef63s/proprietary/framework,system/framework)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/pantech/ef63s/proprietary/vendor,system/vendor)

